({
	appDir:'./',
	baseUrl:'./',
	dir:'./build',
	fileExclusionRegExp: /^(r|build)\.js$/,
	modules:[
		{name:'index'},
		{name:'main'}
		],
	paths:{
		'jquery':'../bower_components/jquery/dist/jquery.min',
		'bootstrap':'../bower_components/bootstrap/dist/js/bootstrap.min',
		'index':'index'
	},
	shim:{
		bootstrap:{
			deps:['jquery']
		},
		index:{
			deps:['jquery']
		}
	}
})